//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/Input/ButtonsInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ButtonsInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ButtonsInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ButtonsInput"",
    ""maps"": [
        {
            ""name"": ""Car"",
            ""id"": ""9e8a07ce-3286-460c-a922-673ee15cad78"",
            ""actions"": [
                {
                    ""name"": ""Red_Press"",
                    ""type"": ""Button"",
                    ""id"": ""58a75380-434a-4261-9303-1a98ad3f1f02"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Red_Release"",
                    ""type"": ""Button"",
                    ""id"": ""e7079715-ddeb-4d26-83f2-07475bd9fa78"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Black_Press"",
                    ""type"": ""Button"",
                    ""id"": ""3cfec8b9-c932-4644-abdf-c194aa26768f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Black_Release"",
                    ""type"": ""Button"",
                    ""id"": ""fd37b0c0-c7c7-47e1-a8f4-b3067770b237"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Blue"",
                    ""type"": ""Button"",
                    ""id"": ""44a97298-9b0a-4162-a77e-72b39ebfef0a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Blue_Release"",
                    ""type"": ""Button"",
                    ""id"": ""1588adf3-e9d6-4550-a27f-7790c3269d58"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Green"",
                    ""type"": ""Button"",
                    ""id"": ""a7979ffb-89a6-47fc-9bfa-902a13f62c24"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Green-Release"",
                    ""type"": ""Button"",
                    ""id"": ""35567f03-5175-4709-9d84-fd51ed66a333"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""White"",
                    ""type"": ""Button"",
                    ""id"": ""4e120b5a-f9a2-41da-b056-2b469348288d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""White_Release"",
                    ""type"": ""Button"",
                    ""id"": ""ecde083f-9d4f-4d0b-8a62-7db4d94e156c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Yellow"",
                    ""type"": ""Button"",
                    ""id"": ""0de40ad6-8755-4e97-a432-15287fbfdfa7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Yellow_Release"",
                    ""type"": ""Button"",
                    ""id"": ""0db4fc1f-abd7-42f6-a3fd-ace5b99fd523"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Aim"",
                    ""type"": ""PassThrough"",
                    ""id"": ""5aaf4771-2f8d-4a4e-9f34-9dcceabbadbf"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""cfbbb2c4-cdec-4705-b2ab-2e54183aba15"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Red_Press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1b9d2079-320d-45fa-811b-410071897322"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Red_Press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1887089f-c32b-43f8-a544-6a2dee1cd9b4"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Black_Press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a9b8a3e0-8b12-4f20-b4c4-050377a633ad"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Black_Press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""203b01a1-ab99-480a-b9e2-5996b065768b"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Blue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""56f16002-ad0b-491d-b140-be7f922c885c"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Blue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dc04cf4e-4502-42de-8b7a-ec394033eda5"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Green"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a2ad1ce0-efab-4b33-8ced-0254fc8396db"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Green"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ec6303a0-06f7-4ca8-9400-141ac12e5628"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""White"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8b3b8bb0-c200-4c0b-9457-b6dfb98f03a0"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""White"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3656bb38-69a4-42c1-9878-ced34fa89d32"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Yellow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""37d55fe4-5730-46a9-a5a5-0c6ce1031de7"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Yellow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d8b53e3a-4039-46af-843c-cde8626b9b1d"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Red_Release"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6e12e1aa-239f-412e-929d-493b5dde602c"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": ""Press(behavior=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Red_Release"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""068fad42-ff05-4d1f-b842-ec8d7602026a"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Black_Release"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b672858d-92a9-4d3b-bffc-080fc784a497"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": ""Press(behavior=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Black_Release"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9805660f-d683-447c-bea6-badbe5c1cdea"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Blue_Release"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""34cbe871-e828-4442-b4f1-2ad85be07e45"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Green-Release"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""54595542-7c71-4b1f-bb0d-e3f5fc1c1657"",
                    ""path"": ""<Keyboard>/o"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""White_Release"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7f328f98-77e2-428c-8c5a-a99d8eaac9c7"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Yellow_Release"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""87e16788-7bef-4f43-ba32-6a9d5a45f8d9"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": ""Press(behavior=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Yellow_Release"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e84b093d-4f0a-4128-b74e-5ba292d71816"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ea0abd57-2f10-488f-9f47-fc887c769eb1"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Solo"",
            ""id"": ""67585c90-e75b-488c-ac94-93b2d215ba42"",
            ""actions"": [
                {
                    ""name"": ""Ing1"",
                    ""type"": ""Button"",
                    ""id"": ""a795f375-9d15-4aa8-8d5a-dd59e74376c9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Ing2"",
                    ""type"": ""Button"",
                    ""id"": ""cf47102f-7b03-4e2a-9305-442b04c134ee"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Ing3"",
                    ""type"": ""Button"",
                    ""id"": ""782f6363-569e-4e7d-a0db-3b101a9f58c1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Ing4"",
                    ""type"": ""Button"",
                    ""id"": ""60885dd3-efc5-42f3-be22-81028ca60bb8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Ing5"",
                    ""type"": ""Button"",
                    ""id"": ""e443fe40-1a14-472d-98f0-0433101a1c4c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Ing6"",
                    ""type"": ""Button"",
                    ""id"": ""41525b6d-84c6-4376-96c9-908d0d7a3866"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Bake"",
                    ""type"": ""Button"",
                    ""id"": ""53d95578-2dfe-45a0-bbe3-fe4d3feaab9f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shoot"",
                    ""type"": ""Button"",
                    ""id"": ""a8f1d7f7-2ec0-4815-978a-12c7580398e9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Zoom"",
                    ""type"": ""Button"",
                    ""id"": ""62976e4b-4ec0-4eaa-a1f6-018851d643e7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Aim"",
                    ""type"": ""PassThrough"",
                    ""id"": ""270313d2-6ce4-4dae-9818-17a1f5ec1b5a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FlyUp"",
                    ""type"": ""Button"",
                    ""id"": ""65e2b16c-0b84-457b-a411-25a393863b94"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FlyDown"",
                    ""type"": ""Button"",
                    ""id"": ""d140fba3-c62b-49f3-a4da-ad30b442d947"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Steer"",
                    ""type"": ""PassThrough"",
                    ""id"": ""a408fe93-a5a5-4d6e-ab5a-00f50363f163"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Brake"",
                    ""type"": ""Button"",
                    ""id"": ""8b79029d-8421-48ef-bce9-2a67cccf7fd3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""03a24bfe-9eef-43c2-9538-80c17a1c74f1"",
                    ""path"": ""<Keyboard>/numpad4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ing1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bc3e4cf0-71ea-4d8f-a310-c0184e5d2a45"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ing1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ddaaf45d-e0e0-44a5-9516-4190c91bfc91"",
                    ""path"": ""<Keyboard>/numpad5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ing2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7991e525-df8e-4d44-b172-afb742a650a9"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ing2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0aab5671-d6ae-43ba-a9a2-51ecadf88a98"",
                    ""path"": ""<Keyboard>/numpad6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ing3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b853f1b7-a405-4dde-99cf-3fccc93d229a"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ing3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""af37c030-3c2b-41a5-83ef-2f06e8887e1d"",
                    ""path"": ""<Keyboard>/numpad1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ing4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""64853990-c8d0-42c6-b9b0-726b2009fb14"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ing4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""467c972e-5bcf-4c76-ac9c-191a9f1d7f31"",
                    ""path"": ""<Keyboard>/numpad2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ing5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cb5b83f5-4d5d-4393-80fc-6b5556a534db"",
                    ""path"": ""<Keyboard>/n"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ing5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c116c784-0001-49da-864d-24cdca2b5e8b"",
                    ""path"": ""<Keyboard>/numpad3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ing6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a25c7b42-2d00-416d-9d01-9673e766ad28"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ing6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2ed8b3ef-132f-4be0-a9f4-eb3c2de6ccb8"",
                    ""path"": ""<Keyboard>/numpadEnter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Bake"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f5276825-2734-42b9-813d-b79e40de5700"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Bake"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""80cab7a2-10f0-425b-a215-e3ac209fcf74"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""28a93f5b-78ff-4201-afe8-8e939fef46df"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""04c03796-62c0-4c95-b3eb-e59735d7e2bd"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d43a5c20-11b8-4c68-952c-7ec67f7114e5"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": ""ScaleVector2(x=0.3,y=0.3)"",
                    ""groups"": """",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dddef050-98af-4e3f-b41f-314c856aaf3c"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FlyUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cbdca225-6a24-448e-8a54-90a7091d18d4"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FlyDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Arrow"",
                    ""id"": ""2196368e-97ef-4099-9a02-98ca0ec4171b"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Steer"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""7400dded-4bdb-4b4d-bf51-b837b324e92f"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Steer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""6e5f45a1-61e4-487c-be45-8b66ca01d90d"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Steer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Arrows"",
                    ""id"": ""28ba5a56-62eb-48c9-b29e-0d74dd39611f"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Brake"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""e7c6ffd2-ccea-4d0f-bf11-67b989b9dea8"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Brake"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""118952b4-12e2-460f-b723-a9a14ddffb68"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Brake"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Car
        m_Car = asset.FindActionMap("Car", throwIfNotFound: true);
        m_Car_Red_Press = m_Car.FindAction("Red_Press", throwIfNotFound: true);
        m_Car_Red_Release = m_Car.FindAction("Red_Release", throwIfNotFound: true);
        m_Car_Black_Press = m_Car.FindAction("Black_Press", throwIfNotFound: true);
        m_Car_Black_Release = m_Car.FindAction("Black_Release", throwIfNotFound: true);
        m_Car_Blue = m_Car.FindAction("Blue", throwIfNotFound: true);
        m_Car_Blue_Release = m_Car.FindAction("Blue_Release", throwIfNotFound: true);
        m_Car_Green = m_Car.FindAction("Green", throwIfNotFound: true);
        m_Car_GreenRelease = m_Car.FindAction("Green-Release", throwIfNotFound: true);
        m_Car_White = m_Car.FindAction("White", throwIfNotFound: true);
        m_Car_White_Release = m_Car.FindAction("White_Release", throwIfNotFound: true);
        m_Car_Yellow = m_Car.FindAction("Yellow", throwIfNotFound: true);
        m_Car_Yellow_Release = m_Car.FindAction("Yellow_Release", throwIfNotFound: true);
        m_Car_Aim = m_Car.FindAction("Aim", throwIfNotFound: true);
        // Solo
        m_Solo = asset.FindActionMap("Solo", throwIfNotFound: true);
        m_Solo_Ing1 = m_Solo.FindAction("Ing1", throwIfNotFound: true);
        m_Solo_Ing2 = m_Solo.FindAction("Ing2", throwIfNotFound: true);
        m_Solo_Ing3 = m_Solo.FindAction("Ing3", throwIfNotFound: true);
        m_Solo_Ing4 = m_Solo.FindAction("Ing4", throwIfNotFound: true);
        m_Solo_Ing5 = m_Solo.FindAction("Ing5", throwIfNotFound: true);
        m_Solo_Ing6 = m_Solo.FindAction("Ing6", throwIfNotFound: true);
        m_Solo_Bake = m_Solo.FindAction("Bake", throwIfNotFound: true);
        m_Solo_Shoot = m_Solo.FindAction("Shoot", throwIfNotFound: true);
        m_Solo_Zoom = m_Solo.FindAction("Zoom", throwIfNotFound: true);
        m_Solo_Aim = m_Solo.FindAction("Aim", throwIfNotFound: true);
        m_Solo_FlyUp = m_Solo.FindAction("FlyUp", throwIfNotFound: true);
        m_Solo_FlyDown = m_Solo.FindAction("FlyDown", throwIfNotFound: true);
        m_Solo_Steer = m_Solo.FindAction("Steer", throwIfNotFound: true);
        m_Solo_Brake = m_Solo.FindAction("Brake", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Car
    private readonly InputActionMap m_Car;
    private List<ICarActions> m_CarActionsCallbackInterfaces = new List<ICarActions>();
    private readonly InputAction m_Car_Red_Press;
    private readonly InputAction m_Car_Red_Release;
    private readonly InputAction m_Car_Black_Press;
    private readonly InputAction m_Car_Black_Release;
    private readonly InputAction m_Car_Blue;
    private readonly InputAction m_Car_Blue_Release;
    private readonly InputAction m_Car_Green;
    private readonly InputAction m_Car_GreenRelease;
    private readonly InputAction m_Car_White;
    private readonly InputAction m_Car_White_Release;
    private readonly InputAction m_Car_Yellow;
    private readonly InputAction m_Car_Yellow_Release;
    private readonly InputAction m_Car_Aim;
    public struct CarActions
    {
        private @ButtonsInput m_Wrapper;
        public CarActions(@ButtonsInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Red_Press => m_Wrapper.m_Car_Red_Press;
        public InputAction @Red_Release => m_Wrapper.m_Car_Red_Release;
        public InputAction @Black_Press => m_Wrapper.m_Car_Black_Press;
        public InputAction @Black_Release => m_Wrapper.m_Car_Black_Release;
        public InputAction @Blue => m_Wrapper.m_Car_Blue;
        public InputAction @Blue_Release => m_Wrapper.m_Car_Blue_Release;
        public InputAction @Green => m_Wrapper.m_Car_Green;
        public InputAction @GreenRelease => m_Wrapper.m_Car_GreenRelease;
        public InputAction @White => m_Wrapper.m_Car_White;
        public InputAction @White_Release => m_Wrapper.m_Car_White_Release;
        public InputAction @Yellow => m_Wrapper.m_Car_Yellow;
        public InputAction @Yellow_Release => m_Wrapper.m_Car_Yellow_Release;
        public InputAction @Aim => m_Wrapper.m_Car_Aim;
        public InputActionMap Get() { return m_Wrapper.m_Car; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CarActions set) { return set.Get(); }
        public void AddCallbacks(ICarActions instance)
        {
            if (instance == null || m_Wrapper.m_CarActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CarActionsCallbackInterfaces.Add(instance);
            @Red_Press.started += instance.OnRed_Press;
            @Red_Press.performed += instance.OnRed_Press;
            @Red_Press.canceled += instance.OnRed_Press;
            @Red_Release.started += instance.OnRed_Release;
            @Red_Release.performed += instance.OnRed_Release;
            @Red_Release.canceled += instance.OnRed_Release;
            @Black_Press.started += instance.OnBlack_Press;
            @Black_Press.performed += instance.OnBlack_Press;
            @Black_Press.canceled += instance.OnBlack_Press;
            @Black_Release.started += instance.OnBlack_Release;
            @Black_Release.performed += instance.OnBlack_Release;
            @Black_Release.canceled += instance.OnBlack_Release;
            @Blue.started += instance.OnBlue;
            @Blue.performed += instance.OnBlue;
            @Blue.canceled += instance.OnBlue;
            @Blue_Release.started += instance.OnBlue_Release;
            @Blue_Release.performed += instance.OnBlue_Release;
            @Blue_Release.canceled += instance.OnBlue_Release;
            @Green.started += instance.OnGreen;
            @Green.performed += instance.OnGreen;
            @Green.canceled += instance.OnGreen;
            @GreenRelease.started += instance.OnGreenRelease;
            @GreenRelease.performed += instance.OnGreenRelease;
            @GreenRelease.canceled += instance.OnGreenRelease;
            @White.started += instance.OnWhite;
            @White.performed += instance.OnWhite;
            @White.canceled += instance.OnWhite;
            @White_Release.started += instance.OnWhite_Release;
            @White_Release.performed += instance.OnWhite_Release;
            @White_Release.canceled += instance.OnWhite_Release;
            @Yellow.started += instance.OnYellow;
            @Yellow.performed += instance.OnYellow;
            @Yellow.canceled += instance.OnYellow;
            @Yellow_Release.started += instance.OnYellow_Release;
            @Yellow_Release.performed += instance.OnYellow_Release;
            @Yellow_Release.canceled += instance.OnYellow_Release;
            @Aim.started += instance.OnAim;
            @Aim.performed += instance.OnAim;
            @Aim.canceled += instance.OnAim;
        }

        private void UnregisterCallbacks(ICarActions instance)
        {
            @Red_Press.started -= instance.OnRed_Press;
            @Red_Press.performed -= instance.OnRed_Press;
            @Red_Press.canceled -= instance.OnRed_Press;
            @Red_Release.started -= instance.OnRed_Release;
            @Red_Release.performed -= instance.OnRed_Release;
            @Red_Release.canceled -= instance.OnRed_Release;
            @Black_Press.started -= instance.OnBlack_Press;
            @Black_Press.performed -= instance.OnBlack_Press;
            @Black_Press.canceled -= instance.OnBlack_Press;
            @Black_Release.started -= instance.OnBlack_Release;
            @Black_Release.performed -= instance.OnBlack_Release;
            @Black_Release.canceled -= instance.OnBlack_Release;
            @Blue.started -= instance.OnBlue;
            @Blue.performed -= instance.OnBlue;
            @Blue.canceled -= instance.OnBlue;
            @Blue_Release.started -= instance.OnBlue_Release;
            @Blue_Release.performed -= instance.OnBlue_Release;
            @Blue_Release.canceled -= instance.OnBlue_Release;
            @Green.started -= instance.OnGreen;
            @Green.performed -= instance.OnGreen;
            @Green.canceled -= instance.OnGreen;
            @GreenRelease.started -= instance.OnGreenRelease;
            @GreenRelease.performed -= instance.OnGreenRelease;
            @GreenRelease.canceled -= instance.OnGreenRelease;
            @White.started -= instance.OnWhite;
            @White.performed -= instance.OnWhite;
            @White.canceled -= instance.OnWhite;
            @White_Release.started -= instance.OnWhite_Release;
            @White_Release.performed -= instance.OnWhite_Release;
            @White_Release.canceled -= instance.OnWhite_Release;
            @Yellow.started -= instance.OnYellow;
            @Yellow.performed -= instance.OnYellow;
            @Yellow.canceled -= instance.OnYellow;
            @Yellow_Release.started -= instance.OnYellow_Release;
            @Yellow_Release.performed -= instance.OnYellow_Release;
            @Yellow_Release.canceled -= instance.OnYellow_Release;
            @Aim.started -= instance.OnAim;
            @Aim.performed -= instance.OnAim;
            @Aim.canceled -= instance.OnAim;
        }

        public void RemoveCallbacks(ICarActions instance)
        {
            if (m_Wrapper.m_CarActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICarActions instance)
        {
            foreach (var item in m_Wrapper.m_CarActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CarActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CarActions @Car => new CarActions(this);

    // Solo
    private readonly InputActionMap m_Solo;
    private List<ISoloActions> m_SoloActionsCallbackInterfaces = new List<ISoloActions>();
    private readonly InputAction m_Solo_Ing1;
    private readonly InputAction m_Solo_Ing2;
    private readonly InputAction m_Solo_Ing3;
    private readonly InputAction m_Solo_Ing4;
    private readonly InputAction m_Solo_Ing5;
    private readonly InputAction m_Solo_Ing6;
    private readonly InputAction m_Solo_Bake;
    private readonly InputAction m_Solo_Shoot;
    private readonly InputAction m_Solo_Zoom;
    private readonly InputAction m_Solo_Aim;
    private readonly InputAction m_Solo_FlyUp;
    private readonly InputAction m_Solo_FlyDown;
    private readonly InputAction m_Solo_Steer;
    private readonly InputAction m_Solo_Brake;
    public struct SoloActions
    {
        private @ButtonsInput m_Wrapper;
        public SoloActions(@ButtonsInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Ing1 => m_Wrapper.m_Solo_Ing1;
        public InputAction @Ing2 => m_Wrapper.m_Solo_Ing2;
        public InputAction @Ing3 => m_Wrapper.m_Solo_Ing3;
        public InputAction @Ing4 => m_Wrapper.m_Solo_Ing4;
        public InputAction @Ing5 => m_Wrapper.m_Solo_Ing5;
        public InputAction @Ing6 => m_Wrapper.m_Solo_Ing6;
        public InputAction @Bake => m_Wrapper.m_Solo_Bake;
        public InputAction @Shoot => m_Wrapper.m_Solo_Shoot;
        public InputAction @Zoom => m_Wrapper.m_Solo_Zoom;
        public InputAction @Aim => m_Wrapper.m_Solo_Aim;
        public InputAction @FlyUp => m_Wrapper.m_Solo_FlyUp;
        public InputAction @FlyDown => m_Wrapper.m_Solo_FlyDown;
        public InputAction @Steer => m_Wrapper.m_Solo_Steer;
        public InputAction @Brake => m_Wrapper.m_Solo_Brake;
        public InputActionMap Get() { return m_Wrapper.m_Solo; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SoloActions set) { return set.Get(); }
        public void AddCallbacks(ISoloActions instance)
        {
            if (instance == null || m_Wrapper.m_SoloActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_SoloActionsCallbackInterfaces.Add(instance);
            @Ing1.started += instance.OnIng1;
            @Ing1.performed += instance.OnIng1;
            @Ing1.canceled += instance.OnIng1;
            @Ing2.started += instance.OnIng2;
            @Ing2.performed += instance.OnIng2;
            @Ing2.canceled += instance.OnIng2;
            @Ing3.started += instance.OnIng3;
            @Ing3.performed += instance.OnIng3;
            @Ing3.canceled += instance.OnIng3;
            @Ing4.started += instance.OnIng4;
            @Ing4.performed += instance.OnIng4;
            @Ing4.canceled += instance.OnIng4;
            @Ing5.started += instance.OnIng5;
            @Ing5.performed += instance.OnIng5;
            @Ing5.canceled += instance.OnIng5;
            @Ing6.started += instance.OnIng6;
            @Ing6.performed += instance.OnIng6;
            @Ing6.canceled += instance.OnIng6;
            @Bake.started += instance.OnBake;
            @Bake.performed += instance.OnBake;
            @Bake.canceled += instance.OnBake;
            @Shoot.started += instance.OnShoot;
            @Shoot.performed += instance.OnShoot;
            @Shoot.canceled += instance.OnShoot;
            @Zoom.started += instance.OnZoom;
            @Zoom.performed += instance.OnZoom;
            @Zoom.canceled += instance.OnZoom;
            @Aim.started += instance.OnAim;
            @Aim.performed += instance.OnAim;
            @Aim.canceled += instance.OnAim;
            @FlyUp.started += instance.OnFlyUp;
            @FlyUp.performed += instance.OnFlyUp;
            @FlyUp.canceled += instance.OnFlyUp;
            @FlyDown.started += instance.OnFlyDown;
            @FlyDown.performed += instance.OnFlyDown;
            @FlyDown.canceled += instance.OnFlyDown;
            @Steer.started += instance.OnSteer;
            @Steer.performed += instance.OnSteer;
            @Steer.canceled += instance.OnSteer;
            @Brake.started += instance.OnBrake;
            @Brake.performed += instance.OnBrake;
            @Brake.canceled += instance.OnBrake;
        }

        private void UnregisterCallbacks(ISoloActions instance)
        {
            @Ing1.started -= instance.OnIng1;
            @Ing1.performed -= instance.OnIng1;
            @Ing1.canceled -= instance.OnIng1;
            @Ing2.started -= instance.OnIng2;
            @Ing2.performed -= instance.OnIng2;
            @Ing2.canceled -= instance.OnIng2;
            @Ing3.started -= instance.OnIng3;
            @Ing3.performed -= instance.OnIng3;
            @Ing3.canceled -= instance.OnIng3;
            @Ing4.started -= instance.OnIng4;
            @Ing4.performed -= instance.OnIng4;
            @Ing4.canceled -= instance.OnIng4;
            @Ing5.started -= instance.OnIng5;
            @Ing5.performed -= instance.OnIng5;
            @Ing5.canceled -= instance.OnIng5;
            @Ing6.started -= instance.OnIng6;
            @Ing6.performed -= instance.OnIng6;
            @Ing6.canceled -= instance.OnIng6;
            @Bake.started -= instance.OnBake;
            @Bake.performed -= instance.OnBake;
            @Bake.canceled -= instance.OnBake;
            @Shoot.started -= instance.OnShoot;
            @Shoot.performed -= instance.OnShoot;
            @Shoot.canceled -= instance.OnShoot;
            @Zoom.started -= instance.OnZoom;
            @Zoom.performed -= instance.OnZoom;
            @Zoom.canceled -= instance.OnZoom;
            @Aim.started -= instance.OnAim;
            @Aim.performed -= instance.OnAim;
            @Aim.canceled -= instance.OnAim;
            @FlyUp.started -= instance.OnFlyUp;
            @FlyUp.performed -= instance.OnFlyUp;
            @FlyUp.canceled -= instance.OnFlyUp;
            @FlyDown.started -= instance.OnFlyDown;
            @FlyDown.performed -= instance.OnFlyDown;
            @FlyDown.canceled -= instance.OnFlyDown;
            @Steer.started -= instance.OnSteer;
            @Steer.performed -= instance.OnSteer;
            @Steer.canceled -= instance.OnSteer;
            @Brake.started -= instance.OnBrake;
            @Brake.performed -= instance.OnBrake;
            @Brake.canceled -= instance.OnBrake;
        }

        public void RemoveCallbacks(ISoloActions instance)
        {
            if (m_Wrapper.m_SoloActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ISoloActions instance)
        {
            foreach (var item in m_Wrapper.m_SoloActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_SoloActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public SoloActions @Solo => new SoloActions(this);
    public interface ICarActions
    {
        void OnRed_Press(InputAction.CallbackContext context);
        void OnRed_Release(InputAction.CallbackContext context);
        void OnBlack_Press(InputAction.CallbackContext context);
        void OnBlack_Release(InputAction.CallbackContext context);
        void OnBlue(InputAction.CallbackContext context);
        void OnBlue_Release(InputAction.CallbackContext context);
        void OnGreen(InputAction.CallbackContext context);
        void OnGreenRelease(InputAction.CallbackContext context);
        void OnWhite(InputAction.CallbackContext context);
        void OnWhite_Release(InputAction.CallbackContext context);
        void OnYellow(InputAction.CallbackContext context);
        void OnYellow_Release(InputAction.CallbackContext context);
        void OnAim(InputAction.CallbackContext context);
    }
    public interface ISoloActions
    {
        void OnIng1(InputAction.CallbackContext context);
        void OnIng2(InputAction.CallbackContext context);
        void OnIng3(InputAction.CallbackContext context);
        void OnIng4(InputAction.CallbackContext context);
        void OnIng5(InputAction.CallbackContext context);
        void OnIng6(InputAction.CallbackContext context);
        void OnBake(InputAction.CallbackContext context);
        void OnShoot(InputAction.CallbackContext context);
        void OnZoom(InputAction.CallbackContext context);
        void OnAim(InputAction.CallbackContext context);
        void OnFlyUp(InputAction.CallbackContext context);
        void OnFlyDown(InputAction.CallbackContext context);
        void OnSteer(InputAction.CallbackContext context);
        void OnBrake(InputAction.CallbackContext context);
    }
}
